/*
 * ultrasonic.h
 *
 *  Created on: Oct 15, 2024
 *      Author: Omar Mohamed
 */

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_


#include "std_types.h"

#define TRIGGER_PORT_ID  PORTD_ID
#define TRIGGER_PIN_ID   PIN7_ID

void Ultrasonic_init(void);
/*
* Description:
* Initialize the ICU driver as required.
* Set up the ICU callback function.
* Set the direction for the trigger pin as output through the GPIO driver.
*/

void Ultrasonic_Trigger(void);
/* Description:
* Send the trigger pulse to the ultrasonic sensor.
* Inputs: None.
* Return: None.
*/

uint16 Ultrasonic_readDistance(void);
/*
 * Description:
 * Send the trigger pulse by using the Ultrasonic_Trigger function.
 *Start the measurement process via the ICU driver.
 *Inputs: None.
 * Return: The measured distance in centimeters.
 */

void Ultrasonic_edgeProcessing(void);
/*
 * Description:
 * This is the callback function called by the ICU driver.
 * It calculates the high time (pulse time) generated by the ultrasonic sensor.
 * Inputs: None.
 * return: None.
 * Additional configurations:
 * The trigger pin should be configurable to be connected to any microcontroller ports and pins.
 */

#endif /* ULTRASONIC_H_ */
